layout_spectrum: 0.8543708673678339
typography_spectrum: 0.5611657667905092
color:
  saturation: 0.05063163605518639
  brandStrength: 0.8998458164278418
  lightness: 0.29318081494420767
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
  rhythmicContrast: 0.9154477471020073
name: Si Conecta
navigation:
  - name: The Best
    id: 4748c749-4ab6-4a32-a7f6-e58f12b6844a
    type: content
  - name: Beautiful!
    id: ee62813b-8065-41aa-a56f-9049f52a68b3
    type: content
  - name: Work  or Fun ??
    id: b115423b-0843-4208-bae3-e3e3ccc00c7b
    type: content
  - name: Best runing couple
    id: 825b4a7d-9dc9-44af-8dd9-0e52b07ecc58
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Si Conecta
